// Use Rest Client Extension 
   // --> code --install-extension humao.rest-client
      // OR --> Ctrl+Shift+X > humao.rest-client

#<Just starts down bellow>

### Root Path
GET http://localhost:8080

### API Route
GET http://localhost:8080/api 

### Machine Info Route
GET http://localhost:8080/api/machine

### OS Route
GET http://localhost:8080/api/os 

### System Info Route
GET http://localhost:8080/api/sys
