// Use Rest Client Extension --> code --install-extension humao.rest-client OR --> Ctrl+Shift+X > humao.rest-client

#<Just starts down bellow>

### GET Root Path
GET http://localhost:8080

### GET API Route
GET http://localhost:8080/api 

### GET Machine Info Route
GET http://localhost:8080/api/machine

### POST Machine Name 
POST http://localhost:8080/api/machine
Content-Type: application/json

{
  "machineName": "vm-dev-08"
}

### GET OS Route
GET http://localhost:8080/api/os 

### GET System Info Route
GET http://localhost:8080/api/sys